spring:
  web:
    resources:
      static-locations: file:./uploads/

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: fupto
    password: 111
    url: jdbc:mariadb://hi.newlecture.com:3306/fuptodb
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

